---
title: "Work"
---

[English](work_english.qmd)

# Publication

## Article

---
bibliography: references.bib
csl: https://www.zotero.org/styles/vancouver-brackets-no-et-al
reference-section-title: Publication

nocite: | 
  # nocite: means expressing bibliography without citation
  @Kogata2022
  @kogata2021
  @hoshino2020
  @iidaka2019
  @xiaofangzhìguang2019
  @kogata2018
---

::: {#refs}
:::

## Book

# Presentation

## Oral

-   [**小方智広**]{.underline}, 飯高哲也. 慢性期統合失調症患者における視覚探索課題に関する研究　―提示視野に関する検討―. 日本作業療法学会（2019）.

-   [**小方智広**]{.underline}, 飯高哲也. 慢性期統合失調症患者の色弁別課題におけるカテゴリカル効果と側性に関する研究. 大学間精神科作業療法ミーティング（2019）.

-   川村匡史, 加藤麗, 鬼頭亜希, [**小方智広,**]{.underline} 星野藍子. 統合失調患者の日常生活動作に関する主観的な時間見積もりの特徴. 日本作業療法学会（2019）.

-   [**小方智広**]{.underline}, 鈴木國文. 統合失調症患者における塗り絵の特徴-色彩知識および彩色理由に着目した検討-. 日本作業療法学会（2019）.

-   [**小方智広**]{.underline}, 鈴木國文. 色の認識と統合失調症―作業療法学から見えるシニフィアンと主体の病理. 精神病理コロック（2017）.

-   [**小方智広**]{.underline}, 鈴木國文. 統合失調症患者の色認識について. 大学間精神科作業療法ミーティング（2017）.

-   [**Tomohiro Kogata**]{.underline}. A study on color recognition in patients with schizophrenia. Nagoya Yonsei University Research Exchange Meeting on Health Sciences (2016).

## Poster

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Hiroyuki Yamamoto. Functional significance of resting-state fMRI in relation with fixational eye movement. Annual Meeting of the Organization for Human Brain Mapping (2019).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Epifanio Bagarinao. Classification of resting-state fMRI in autism and control subjects using a support vector machine. Annual Meeting of the Organization for Human Brain Mapping (2017).

-   Tetsuya Iidaka, **Tomohiro Kogata**, Epifanio Bagarinao. Effects of global signal regression and head movement on connectivity analysis using resting state functional magnetic resonance imaging. Neuroscience (2017).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Yoko Mano. A resting state fMRI study in autism spectrum disorder. BrainConnects (2018).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Yoko Mano. Thalamocortical and corticocortical hyperconnectivity in autism spectrum disorder. Annual Meeting of the Organization for Human Brain Mapping (2018).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Yoko Mano. Network analysis of resting-state fMRI from a multi-site database: A comparison between autism spectrum disorder patients and control subjects. Neuroscience (2018).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Yoko Mano. Thalamocortical and corticocortical hyperconnectivity in autism spectrum disorder. Annual Meeting of the Organization for Human Brain Mapping (2018).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Yoko Mano. A resting state fMRI study in autism spectrum disorder. BrainConnects (2018).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Epifanio Bagarinao. Effects of global signal regression and head movement on connectivity analysis using resting state functional magnetic resonance imaging. Neuroscience (2017).

-   Tetsuya Iidaka, [**Tomohiro Kogata**]{.underline}, Epifanio Bagarinao. Classification of resting-state fMRI in autism and control subjects using a support vector machine. Annual Meeting of the Organization for Human Brain Mapping (2017).

# Academic Activities

-   [BrainConnects (2022)](https://sites.google.com/view/brainconnects2022), Organizing Committee.

-   名大研究室の扉 in 河合塾（2019）, 講師.

-   第17回東海北陸作業療法学会（2017）, 学会運営委員.

# Awards

-   第53回日本作業療法学会（2019）, [優秀演題賞](https://www.jstage.jst.go.jp/article/jotr/39/2/39_133/_article/-char/ja/). 「慢性期統合失調症患者における視覚探索課題に関する研究　―提示視野に関する検討―」

# Funding

-   公益財団法人フランスベッド・メディカルホームケア研究・助成財団平成30年度研究助成. 「日常生活環境下における統合失調症患者の視覚世界に関する研究－ウェアラブル端末を用いた買物課題の基礎的検討－」（研究代表者）
